// vue3-notes/Project_text/mulity_slot/src/components/Card.vue
<template>
    <div class="container">
       <header>
        <img src="https://pbs.twimg.com/media/F_IbH8JawAAfbhv?format=jpg&name=small" alt="">
        <slot name="header">

        </slot>
       </header>

       <main>
        <img src="https://pbs.twimg.com/media/F_dGbrWbUAAy4bt?format=jpg&name=small" alt="">
         <slot >

         </slot>
       </main>

       <footer>

        <img src="https://pbs.twimg.com/media/F_XvyYOaIAAYTS6?format=jpg&name=small" alt="">
         <slot name="footer">

         </slot>
       </footer>
    </div>
</template>



<style>
    footer{
        background-color: #333;
        color: #fff;
        padding: 10px;
    }

    header{
        background-color: #333;
        color: #fff;
        padding: 10px;
    }

    main{
        background-color: #fff;
        color: #333;
        padding: 10px;
    }

</style>

// React/card_components/src/Card.jsx
function Card() {
  return (
    <div className="card">
      {/* 图片 */}
      <img className="card-image" src="https://pbs.twimg.com/media/GXHlxnmbEAA5T8k?format=jpg&name=small" alt="this is a profile picture" width={150} height={150}></img>
      {/* 标题 */}
      <h2 className="card-title"> A xyn</h2>
      {/* 描述 */}
      <p className="card-text">I make a picture gem</p>
    </div>
  );
}

export default Card;
